os:
- linux
services:
- docker
language: node_js
node_js:
- 6.9.5
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - node
  - node_modules
  - "$HOME/.m2"
  - "$HOME/.yarn-cache"
env:
  global:
  - NODE_VERSION=6.9.5
  - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
  - SPRING_JPA_SHOW_SQL=false
  - HEROKU_API_KEY=QcLTwWlnffXZx227VlL8rik2L1yE2JEPSYNZbvkA3sE44zNjik06B3PPFqn2FCbPKGBCkfnE2W2cccHMSr760AxykK/TrIiu0KpFRersPnj2P2rVnb0eX+Bu3OWTj1DVo406/xxyglsM1wW8Tqi1NadBCjbFrijOYcIs2nqd6eEmAa/8U9llnW3y5Ny3ePygEJo4ldvtqjFGzetotu3pF6YM2RteNdk2tsoAKVfMQzt7JNQlLA5YJ4fZvTaTqf1IwX/aIY2j2d+cj15dh+EFsiOYOcXYKFb02Bdbq36eu6nZRqosSDtfrYhzEgBYXblhrbezJmrvgtTeR9axEOVdEwo4jRusJ9qnB6dojU2y3gRY5csnJCGfWW6zXOnz8kzsre24+se0sEVYJQe8PGJHS0bDYT2ps/GMV5uQi5HKdcXiD9tYUPTXs+nxgMqmy+d5xau9UMNpUxsFSAPiT80XXwwSI1S6PDpSiesEiTGtq/cDnjWQ65x5cbWvtt0JHckIqkfdIeKoRoFd+Bgs0sECd1g8LBDtaRwqRUhMyI3YoXVd4YbedGaS3PNBOQ7vcUXLSgAWxJXlgXLjavsF+GhvWVnQnGbvPn55eyvJwXLIANuEDGLOuGHQ5iqzYfFW3WZUMKlyTZsggjQkS3akxYL2oSmnSniBNnKD3hurgURPbkE=
before_install:
- jdk_switcher use oraclejdk8
- java -version
- sudo /etc/init.d/mysql stop
- sudo /etc/init.d/postgresql stop
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
install:
- yarn install
script:
- chmod +x mvnw
- "./mvnw clean test"
- yarn test
- "./mvnw com.heroku.sdk:heroku-maven-plugin:1.1.1:deploy-war -DskipTests -Pprod -Dheroku.appName=torgcrmce-developer"
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false