version: '2'
services:
    torgcrm-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/TorgCRM/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=TorgCRM
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
